version: 2.1
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: run build file
          command: ./build.sh
  test-cases:
    docker:
      - image: g33tha/circleci
    steps:
      - checkout
      #- run: npm cache clean --force
      - run: npm install -g @angular/cli
      - run: cd src/app/client/
      - run: npm install
      - run: ng lint
      - run: ng build --prod
      - run: npm run test-with-coverage
      - run:
          name: Add comment on PR
          command: |
            CIRCLE_PR_NUMBER=$(echo $CI_PULL_REQUEST |rev| cut -d '/' -f 1 | rev)
            prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/G33tha/sunbird-portal/pulls/$CIRCLE_PR_NUMBER)
            branchname=$(echo "${prdata}" | jq '.base.ref')
            branch=${branchname//\"/}
            username=$(echo "${prdata}" | jq '.user.login')
            contributor=${username//\"/}
         
            curl \
             -X POST \
             -u $GITHUB_USER_TOKEN:x-oauth-basic \
             -d '{"body": "Hello @'"$contributor"'<br/><br/> This is a auto-generated response. <br/><br/>"}' \
             https://api.github.com/repos/G33tha/sunbird-portal/issues/$CIRCLE_PR_NUMBER/comments
 
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-cases
          requires: build
   
            
      


